nohup llamafactory-cli train \
    --stage sft \
    --do_train \
    --model_name_or_path model_dir \
    --dataset sotopia_omega \
    --dataset_dir ./data \
    --finetuning_type lora \
    --output_dir by_your_self \
    --overwrite_cache \
    --overwrite_output_dir \
    --preprocessing_num_workers 16 \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 16 \
    --lr_scheduler_type cosine \
    --logging_steps 200 \
    --warmup_steps 60 \
    --save_steps 200 \
    --eval_steps 200 \
    --evaluation_strategy steps \
    --load_best_model_at_end \
    --learning_rate 5e-5 \
    --num_train_epochs 3.0 \
    --val_size 0.1 \
    --plot_loss \
    --fp16 \
    --cutoff_len 4096 \
    --warmup_ratio 0.03 \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_target all \
    --template mistral \
    --use_unsloth True \
    > lora_sft_train_mistral.log 2>&1 &